### ISSUE TITLE
Entire world goes blank when using Runic Altar and Botanical Brewery

### ISSUE THREAD

**Issue by TalisRegis20** [VazkiisMods/Botania#3736]
Forge version:  1.16.5 - 36.1.16
Botania version:  1.16.5 - 416

# Further Information
Link to crash log: No crash
Steps to reproduce:
1. Throw any appropriate item(s) on the Runic Altar/Brewery to start crafting
2.  Look at the Runic Altar (or Brewery with Wand of the Forest in hand)

What I expected to happen:
The runes would craft normally.

What happened instead:
They did, but looking at the Runic Altar when the Altar is receiving mana to craft the runes it causes everything to de-render. Looking away from the Altar makes everything appear again. The only things that can be seen are the tops of liquids, the items in the Altar, and mana bursts. The same thing happens with the Botanical Brewery except only if you are holding a Wand of the Forest.

**Comment by williewillus** [comment]
What's your mod list? This has been known to happen with Immersive Portals and also maybe optifine

**Comment by TalisRegis20** [comment]
I am using Immersive Portals, so that might be it. Here's the mod list:
(https://gist.github.com/TalisRegis20/2bdf698f001e904e942f66b3492172be)

**Comment by crabdancing** [comment]
This still occurs in 2024. Def not 'completed'.

**Comment by anoomolu** [comment]
> This still occurs in 2024. Def not 'completed'.

Feel free to open a new issue with steps to reproduce the problem if it’s still occurring on the latest Botania release.
